config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'about', to: 'pages#about'  
  root 'pages#home'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum:3, maximum:50}
  validates :description, presence: true, length: {minimum:10, maximum:300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true,
                   uniqueness: true,
                   length: {minimum:3, maximum:25}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false },
  format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  include Pagy::Backend
  allow_browser versions: :modern

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @pagy, @articles = pagy(Article.all)
  end


  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:error] = "Article was successfully deleted"
    redirect_to articles_path(params[:id])
  end


  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids:[])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def index
    @pagy, @categories = pagy(Category.all)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully"
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category was successfully updated"
      redirect_to categpry_path(@category)
    end
  end

  def show
    @category = Category.find(params[:id])
    @pagy, @category_articles = pagy(@category.articles)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    #redirect_to categories_path unless current_user&.admin? #solucion de Claude
    if !current_user&.admin?#!logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    #debugger
    user = User.find_by(email: params["email"].downcase)
    if user && user.authenticate(params["password"])
      session[:user_id] = user.id
      flash[:notice] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There is something wrong with your login information"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @pagy, @users = pagy(User.all)
  end
  
  def new
    @user = User.new  
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update 
    if @user.update(user_params)
      flash[:notice] = "Your account was updated successfully"
      redirect_to articles_path
    end
  end

  def show 
    @pagy, @articles = pagy(@user.articles)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles crates by user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if logged_in? && current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def gravatar_for(user, options= {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row justify-content-center mb-4">
    <div class="col-md-8">
      <div class="card shadow-sm bg-light text-dark">
        <div class="card-body">
          <h4 class="article-title">
            <%= link_to article.title, article_path(article), class: "text-decoration-none text-primary" %>
          </h4>
          <p class="text-muted article-body">
            <%= truncate(article.description, length: 100) %>
          </p>
          <p class="text-muted article-body">
            <strong>Creation date : </strong><%= article.created_at.strftime("%d/%m/%Y") %>
          </p>
          <% if article.categories.any? %>
            <strong>Categories : </strong><%= render article.categories%>
          <% end %>
          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <div class="d-flex gap-2 mt-3">
              <%= link_to 'Edit article', edit_article_path(article), class: "btn btn-primary glow-hover" %>
              <%= link_to 'Delete this article', article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?" }, class: "btn btn-danger glow-hover" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<br>
<%= render "shared/errors", obj: @article %>
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6"> <!-- Puedes ajustar a col-md-6 o 5 si quieres más estrecho -->
      
      <%= form_for(@article, html: { class: "border p-4 rounded shadow-sm bg-light" }) do |f| %>
        
        <div class="mb-3">
          <%= f.label :title, class: "form-label" %>
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
        
        <div class="mb-3">
          <%= f.label :description, class: "form-label" %>
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of the article" %>
        </div>
        <div class="d-flex flex-wrap gap-3">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <div class="form-check">
              <%= cb.checkbox(class: "form-check-input") %>
              <%= cb.label(class: "form-check-label") %>
            </div>
          <% end %>
        </div>
        <div class="d-grid gap-2 mt-4">
          <%= f.submit @article.persisted? ? "Update Article" : "Create Article", class: "btn btn-primary btn-lg" %>
        </div>
      <% end %>
      <div class="text-center mt-3">
        [<%= link_to 'Cancel request and return to articles listing', articles_path, class: "btn btn-link" %>]
      </div>

    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mb-4 text-dark">Listing all articles</h1>
<%= render 'article', obj: @articles %>
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy)if @pagy.pages > 1 %>
</div>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container mt-4">
  <h2 class="text-center mb-4 text-dark">
    Title: <%= @article.title %>
  </h2>
  <div class="card shadow-sm bg-light text-dark">
    <div class="card-body">
      <div class="row">
        <div class="col-md-6 mx-auto text-center">
          <h3>Created by:</h2>
          <%= gravatar_for(@article.user, size: 150) %><br>
          <%= link_to "#{@article.user.username}", user_path(@article.user), class: "mt-4"%>
        </div>
      </div>
      <h4 class="text-center description mt-3"><strong>Description:</strong></h4>
      <hr class="border-light">
      <p><%= simple_format(@article.description) %></p>
      <% if @article.categories.any? %>
        <p>
          Categories : <%= render @article.categories %>
        </p>
      <% end %>
      <div class="d-flex justify-content-left gap-2 mt-4 article-actions">
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
          <%= link_to 'Edit article', edit_article_path(@article), class: "btn btn-primary" %>
          <%= link_to 'Delete this article', article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?" }, class: "btn btn-danger" %>
        <% end%>  
        <%= link_to 'View all articles', articles_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge">
    <%= link_to "#{category.name}",category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      
      <%= form_with model: @category, local: true,  html: { class: "border p-4 rounded shadow-sm bg-light" } do |f| %>
        
        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
        </div>
        
        <div class="d-grid gap-2">
          <%= f.submit 'Submit', class: "btn btn-primary btn-lg" %>
        </div>

      <% end %>

      <div class="text-center mt-3">
        [<%= link_to 'Are u not register?', signup_path, class: "btn btn-link" %>]
      </div>

    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Edit Category Name</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Listing All Categories</h1>
<div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy)if @pagy.pages > 1 %>
</div>
<div align = "center">
    <% @categories.each do |category| %>
    <ul class="list-unstyled">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <li class="fs-5">
                            <%= link_to "#{category.name}", category_path(category), class: "text-decoration-none" %>
                        </li>
                        <% if logged_in? and current_user.admin?  %>
                            <div class="d-flex justify-content-center gap-2 mt-3">
                            <%= link_to 'Edit category', edit_category_path(category), class: "btn btn-primary btn-sm glow-hover" %>
                            <%= link_to 'Delete this category', category_path(category), method: :delete, data: { confirm: "Are you sure you want to delete the user?" }, class: "btn btn-danger btn-sm glow-hover" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </ul>
    <% end %>

</div>

app/views/categories/new.html.erb
<h1>Create New Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mb-4 text-dark">
    <%= "Category : #{@category.name}" %>
</h1>
<%= render 'articles/article', obj: @category_articles %>
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="https://github.com/Capablanc4/alpha-blog">Repository</a>
            by <a href="https://www.youtube.com/@G4briel1337">Rightm4t3</a>
        </small>
        <nav>
            <ul>
                <li>
                    <%= link_to 'About', about_path %>
                </li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%= msg if msg.is_a?(String) %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark-bg navbar-custom">
  <div class="container-fluid">
    <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if logged_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Users', users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Articles', articles_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories <%= "Admin" if current_user.admin? %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Categories", categories_path, class: "dropdown-item" %></li>
              <% if current_user.admin? %>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to 'Create New Category', new_category_path, class: "dropdown-item" %></li>
                  <li><hr class="dropdown-divider"></li>
              <% end %>
              <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %></li>
              <% end %>  
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Your Profile <%= "Admin" if current_user.admin? %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path, class: "dropdown-item" %></li>
              <li><%= link_to 'Edit your profile', edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to 'View your profile', user_path(current_user), class: "dropdown-item"  %></li>
            </ul>
          </li>
          
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
        
        <!-- CAJA DE BUSQUEDA Y BOTON
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        -->
      <% else %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Users', users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Articles', articles_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories <%= "Admin" if current_user&.admin? %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Categories", categories_path, class: "dropdown-item" %></li>
              <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
        </ul>        
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", type: "module", "data-turbo-track": "reload", defer: true %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

  </head>

  <body data-turbo="false" class="fondo">
    <%= render 'layouts/navigation' %>
    <br>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <br>
    <%#= pagy_bootstrap_nav(@pagy) if @pagy %>

    <%# debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page of my blog app</h1>
<%= link_to "Home" , root_path %>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>ALPHA BLOG</h1>
</div>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="d-flex justify-content-center">
      <%= link_to 'Sign up now', signup_path, class: "btn btn-custom-green btn-lg btn-dark" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">
          <%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:
        </h4>
        <hr>
        <ul class="mb-0">
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      
      <%= form_with model: @user, local: true,  html: { class: "border p-4 rounded shadow-sm bg-light" } do |f| %>
        
        <div class="mb-3">
          <%= f.label :username, class: "form-label" %>
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
        
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>

        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>

        <div class="d-grid gap-2">
          <%= f.submit @user.persisted? ? "Updated Account" : "Sign up", class: "btn btn-primary btn-lg" %>
        </div>

      <% end %>

      <div class="text-center mt-3">
        [<%= link_to 'Are u not register?', signup_path, class: "btn btn-link" %>]
      </div>

    </div>
  </div>
</div>

app/views/users/_user.html.erb
<% obj.each do |user| %>
  <div class="row justify-content-center mb-4">
    <div class="col-md-8">
      <div class="card shadow-sm bg-light text-dark">
        <div class="card-body text-center">
          <h4 class="article-title mb-3">
            <%= link_to gravatar_for(user, size: 150), user_path(user), class: "d-block mb-3 mx-auto" %>
          </h4>
          <ul class="text-center mx-auto">
            <li>
              <%= link_to user.username, user_path(user), class: "text-decoration-none text-primary" %>
            </li>
            <li class= "text-muted mb-1">  
            <strong>Email:</strong>
            <%= user.email%>    
            </li>
            <li , class= "text-muted mb-1">
              <strong>Creation date:</strong> 
              <%= user.created_at.strftime("%d/%m/%Y")%>
            </li>
            <li class= "mb-2">
              <%= pluralize(user.articles.count, "article")%> 
            </li>
          </ul>
          <% if logged_in? and current_user.admin?  %>
            <div class="d-flex justify-content-center gap-2 mt-3">
              <%= link_to 'Edit user', edit_user_path(user), class: "btn btn-primary btn-sm glow-hover" %>
              <%= link_to 'Delete this user', user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user?" }, class: "btn btn-danger btn-sm glow-hover" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>  
<% end %>

app/views/users/edit.html.erb
<h1 align = "center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Alpha-blog Bloggers</h1>

<%= render 'user', obj: @users %>
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy)if @pagy.pages > 1 %>
</div>

app/views/users/new.html.erb
<br>
<h1 align= "center">Signup for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>/s page</h1>
<div class="row">
    <div class="col-md-6 mx-auto text-center">
        <%= gravatar_for @user, size: 150%>
    </div>
</div>
<h4>
    <%= @user.username %>'s articles
</h4>
<%= render '/articles/article', obj: @articles %>
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy)if @pagy.pages > 1 %>
</div>